import { Element } from "../types";

export const ELEMENTS: Element[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydro",
    atomic_mass: "1.008",
    category: "phi kim lưỡng nguyên tử",
    group: 1,
    period: 1,
    phase: "Khí",
    summary: "Hydro là nguyên tố nhẹ nhất, chiếm 75% khối lượng vũ trụ. Không màu, không mùi, cực kỳ dễ cháy.",
    appearance: "khí không màu",
    melt: 13.99,
    boil: 20.271,
    density: 0.08988,
    discovered_by: "Henry Cavendish",
    named_by: "Antoine Lavoisier",
    color: "#3dff00",
    xpos: 1,
    ypos: 1
  },
  {
    number: 2,
    symbol: "He",
    name: "Heli",
    atomic_mass: "4.0026",
    category: "khí hiếm",
    group: 18,
    period: 1,
    phase: "Khí",
    summary: "Heli là khí hiếm, trơ, nhẹ thứ hai. Dùng trong khinh khí cầu và làm chất làm lạnh siêu dẫn.",
    appearance: "khí không màu",
    melt: 0.95,
    boil: 4.222,
    density: 0.1786,
    discovered_by: "Pierre Janssen",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 1
  },
  {
    number: 3,
    symbol: "Li",
    name: "Liti",
    atomic_mass: "6.94",
    category: "kim loại kiềm",
    group: 1,
    period: 2,
    phase: "Rắn",
    summary: "Liti là kim loại nhẹ nhất, phản ứng mạnh. Ứng dụng quan trọng nhất là trong pin sạc hiện đại.",
    appearance: "trắng bạc",
    melt: 453.65,
    boil: 1603,
    density: 0.534,
    discovered_by: "Johan August Arfwedson",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 2
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryli",
    atomic_mass: "9.0122",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 2,
    phase: "Rắn",
    summary: "Beryli cứng, nhẹ, có điểm nóng chảy cao. Dùng trong hợp kim hàng không và cửa sổ tia X.",
    appearance: "trắng xám",
    melt: 1560,
    boil: 2742,
    density: 1.85,
    discovered_by: "Louis Nicolas Vauquelin",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 2
  },
  {
    number: 5,
    symbol: "B",
    name: "Bo",
    atomic_mass: "10.81",
    category: "á kim",
    group: 13,
    period: 2,
    phase: "Rắn",
    summary: "Bo là á kim quan trọng trong công nghiệp thủy tinh chịu nhiệt và là vi chất cho cây trồng.",
    appearance: "đen nâu",
    melt: 2349,
    boil: 4273,
    density: 2.08,
    discovered_by: "Joseph Louis Gay-Lussac",
    named_by: null,
    color: "#ff00ff",
    xpos: 13,
    ypos: 2
  },
  {
    number: 6,
    symbol: "C",
    name: "Cacbon",
    atomic_mass: "12.011",
    category: "phi kim đa nguyên tử",
    group: 14,
    period: 2,
    phase: "Rắn",
    summary: "Cacbon là nền tảng của sự sống. Tồn tại dưới dạng than chì mềm hoặc kim cương cực cứng.",
    appearance: "đen hoặc trong suốt",
    melt: 3823,
    boil: 4300,
    density: 2.267,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#3dff00",
    xpos: 14,
    ypos: 2
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitơ",
    atomic_mass: "14.007",
    category: "phi kim lưỡng nguyên tử",
    group: 15,
    period: 2,
    phase: "Khí",
    summary: "Nitơ chiếm 78% khí quyển. Là thành phần thiết yếu của protein và DNA trong mọi sinh vật.",
    appearance: "khí không màu",
    melt: 63.15,
    boil: 77.36,
    density: 1.2506,
    discovered_by: "Daniel Rutherford",
    named_by: "Jean-Antoine Chaptal",
    color: "#3dff00",
    xpos: 15,
    ypos: 2
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxy",
    atomic_mass: "15.999",
    category: "phi kim lưỡng nguyên tử",
    group: 16,
    period: 2,
    phase: "Khí",
    summary: "Oxy duy trì sự cháy và sự hô hấp. Chiếm khoảng 21% bầu khí quyển Trái đất.",
    appearance: "khí không màu",
    melt: 54.36,
    boil: 90.188,
    density: 1.429,
    discovered_by: "Carl Wilhelm Scheele",
    named_by: "Antoine Lavoisier",
    color: "#3dff00",
    xpos: 16,
    ypos: 2
  },
  {
    number: 9,
    symbol: "F",
    name: "Flo",
    atomic_mass: "18.998",
    category: "phi kim lưỡng nguyên tử",
    group: 17,
    period: 2,
    phase: "Khí",
    summary: "Flo là phi kim phản ứng mạnh nhất. Hợp chất của nó dùng trong kem đánh răng và sản xuất Teflon.",
    appearance: "khí vàng nhạt",
    melt: 53.48,
    boil: 85.03,
    density: 1.696,
    discovered_by: "André-Marie Ampère",
    named_by: "Humphry Davy",
    color: "#3dff00",
    xpos: 17,
    ypos: 2
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomic_mass: "20.180",
    category: "khí hiếm",
    group: 18,
    period: 2,
    phase: "Khí",
    summary: "Neon là khí hiếm trơ, phát ra ánh sáng đỏ cam rực rỡ trong các ống phóng điện.",
    appearance: "khí không màu",
    melt: 24.56,
    boil: 27.07,
    density: 0.9002,
    discovered_by: "Morris Travers",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 2
  },
  {
    number: 11,
    symbol: "Na",
    name: "Natri",
    atomic_mass: "22.990",
    category: "kim loại kiềm",
    group: 1,
    period: 3,
    phase: "Rắn",
    summary: "Natri là kim loại mềm, phản ứng mãnh liệt với nước. Là thành phần của muối ăn NaCl.",
    appearance: "trắng bạc",
    melt: 370.944,
    boil: 1156.09,
    density: 0.968,
    discovered_by: "Humphry Davy",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 3
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magie",
    atomic_mass: "24.305",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 3,
    phase: "Rắn",
    summary: "Magie nhẹ, cháy với ánh sáng trắng chói. Là khoáng chất quan trọng cho xương và cơ.",
    appearance: "xám trắng",
    melt: 923,
    boil: 1363,
    density: 1.738,
    discovered_by: "Joseph Black",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 3
  },
  {
    number: 13,
    symbol: "Al",
    name: "Nhôm",
    atomic_mass: "26.982",
    category: "kim loại sau chuyển tiếp",
    group: 13,
    period: 3,
    phase: "Rắn",
    summary: "Nhôm nhẹ, bền, chống ăn mòn. Dùng trong vỏ máy bay, lon nước giải khát và xây dựng.",
    appearance: "xám bạc",
    melt: 933.47,
    boil: 2743,
    density: 2.70,
    discovered_by: "Hans Christian Ørsted",
    named_by: "Humphry Davy",
    color: "#cccccc",
    xpos: 13,
    ypos: 3
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silic",
    atomic_mass: "28.085",
    category: "á kim",
    group: 14,
    period: 3,
    phase: "Rắn",
    summary: "Silic là nền tảng của công nghệ điện tử hiện đại, dùng làm chip bán dẫn và pin mặt trời.",
    appearance: "xám xanh ánh kim",
    melt: 1687,
    boil: 3538,
    density: 2.329,
    discovered_by: "Jöns Jacob Berzelius",
    named_by: "Thomas Thomson",
    color: "#ff00ff",
    xpos: 14,
    ypos: 3
  },
  {
    number: 15,
    symbol: "P",
    name: "Photpho",
    atomic_mass: "30.974",
    category: "phi kim đa nguyên tử",
    group: 15,
    period: 3,
    phase: "Rắn",
    summary: "Photpho có hai dạng chính: trắng (dễ cháy, độc) và đỏ (an toàn, dùng làm đầu diêm).",
    appearance: "trắng hoặc đỏ",
    melt: 317.3,
    boil: 553.7,
    density: 1.823,
    discovered_by: "Hennig Brand",
    named_by: null,
    color: "#3dff00",
    xpos: 15,
    ypos: 3
  },
  {
    number: 16,
    symbol: "S",
    name: "Lưu huỳnh",
    atomic_mass: "32.06",
    category: "phi kim đa nguyên tử",
    group: 16,
    period: 3,
    phase: "Rắn",
    summary: "Lưu huỳnh màu vàng, dùng sản xuất axit sunfuric, phân bón và lưu hóa cao su.",
    appearance: "vàng chanh",
    melt: 388.36,
    boil: 717.8,
    density: 2.07,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#3dff00",
    xpos: 16,
    ypos: 3
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Clo",
    atomic_mass: "35.45",
    category: "phi kim lưỡng nguyên tử",
    group: 17,
    period: 3,
    phase: "Khí",
    summary: "Clo là khí độc màu vàng lục, dùng để khử trùng nước sinh hoạt và sản xuất chất tẩy rửa.",
    appearance: "vàng lục",
    melt: 171.6,
    boil: 239.11,
    density: 3.2,
    discovered_by: "Carl Wilhelm Scheele",
    named_by: null,
    color: "#3dff00",
    xpos: 17,
    ypos: 3
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomic_mass: "39.948",
    category: "khí hiếm",
    group: 18,
    period: 3,
    phase: "Khí",
    summary: "Argon là khí hiếm trơ, dùng trong bóng đèn và hàn kim loại để ngăn oxy hóa.",
    appearance: "khí không màu",
    melt: 83.81,
    boil: 87.302,
    density: 1.784,
    discovered_by: "Lord Rayleigh",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 3
  },
  {
    number: 19,
    symbol: "K",
    name: "Kali",
    atomic_mass: "39.098",
    category: "kim loại kiềm",
    group: 1,
    period: 4,
    phase: "Rắn",
    summary: "Kali là kim loại kiềm cực kỳ phản ứng, cần thiết cho chức năng thần kinh và cơ bắp.",
    appearance: "trắng bạc",
    melt: 336.53,
    boil: 1032,
    density: 0.862,
    discovered_by: "Humphry Davy",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 4
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Canxi",
    atomic_mass: "40.078",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 4,
    phase: "Rắn",
    summary: "Canxi là kim loại kiềm thổ, thành phần chính của xương, răng và vỏ sò.",
    appearance: "trắng bạc",
    melt: 1115,
    boil: 1757,
    density: 1.54,
    discovered_by: "Humphry Davy",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 4
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandi",
    atomic_mass: "44.956",
    category: "kim loại chuyển tiếp",
    group: 3,
    period: 4,
    phase: "Rắn",
    summary: "Scandi dùng trong hợp kim nhôm siêu bền cho gậy bóng chày và linh kiện máy bay.",
    appearance: "trắng bạc",
    melt: 1814,
    boil: 3109,
    density: 2.985,
    discovered_by: "Lars Fredrik Nilson",
    named_by: null,
    color: "#ffff00",
    xpos: 3,
    ypos: 4
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titan",
    atomic_mass: "47.867",
    category: "kim loại chuyển tiếp",
    group: 4,
    period: 4,
    phase: "Rắn",
    summary: "Titan siêu bền, nhẹ và chống ăn mòn. Dùng trong y tế (xương nhân tạo) và hàng không.",
    appearance: "bạc kim loại",
    melt: 1941,
    boil: 3560,
    density: 4.506,
    discovered_by: "William Gregor",
    named_by: "Martin Heinrich Klaproth",
    color: "#ffff00",
    xpos: 4,
    ypos: 4
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadi",
    atomic_mass: "50.942",
    category: "kim loại chuyển tiếp",
    group: 5,
    period: 4,
    phase: "Rắn",
    summary: "Vanadi dùng chủ yếu làm phụ gia thép để tăng độ cứng và khả năng chịu nhiệt.",
    appearance: "xám bạc",
    melt: 2183,
    boil: 3680,
    density: 6.11,
    discovered_by: "Andrés Manuel del Río",
    named_by: "Ismael Rioja",
    color: "#ffff00",
    xpos: 5,
    ypos: 4
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Crom",
    atomic_mass: "51.996",
    category: "kim loại chuyển tiếp",
    group: 6,
    period: 4,
    phase: "Rắn",
    summary: "Crom tạo độ bóng và chống gỉ cho thép không gỉ. Hợp chất của nó có nhiều màu sắc.",
    appearance: "xám bạc",
    melt: 2180,
    boil: 2944,
    density: 7.19,
    discovered_by: "Louis Nicolas Vauquelin",
    named_by: null,
    color: "#ffff00",
    xpos: 6,
    ypos: 4
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Mangan",
    atomic_mass: "54.938",
    category: "kim loại chuyển tiếp",
    group: 7,
    period: 4,
    phase: "Rắn",
    summary: "Mangan quan trọng trong sản xuất thép và pin khô. Là vi chất cần thiết cho xương.",
    appearance: "trắng bạc",
    melt: 1519,
    boil: 2334,
    density: 7.21,
    discovered_by: "Johan Gottlieb Gahn",
    named_by: null,
    color: "#ffff00",
    xpos: 7,
    ypos: 4
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Sắt",
    atomic_mass: "55.845",
    category: "kim loại chuyển tiếp",
    group: 8,
    period: 4,
    phase: "Rắn",
    summary: "Sắt là kim loại quan trọng nhất trong công nghiệp. Có trong huyết sắc tố vận chuyển oxy.",
    appearance: "xám bạc",
    melt: 1811,
    boil: 3134,
    density: 7.874,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 8,
    ypos: 4
  },
  {
    number: 27,
    symbol: "Co",
    name: "Coban",
    atomic_mass: "58.933",
    category: "kim loại chuyển tiếp",
    group: 9,
    period: 4,
    phase: "Rắn",
    summary: "Coban dùng trong siêu hợp kim và pin lithium-ion. Tạo màu xanh lam đẹp cho gốm sứ.",
    appearance: "xám bạc",
    melt: 1768,
    boil: 3200,
    density: 8.9,
    discovered_by: "Georg Brandt",
    named_by: null,
    color: "#ffff00",
    xpos: 9,
    ypos: 4
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Niken",
    atomic_mass: "58.693",
    category: "kim loại chuyển tiếp",
    group: 10,
    period: 4,
    phase: "Rắn",
    summary: "Niken chống oxy hóa tốt, dùng trong thép không gỉ, tiền xu và pin sạc.",
    appearance: "trắng bạc",
    melt: 1728,
    boil: 3003,
    density: 8.908,
    discovered_by: "Axel Fredrik Cronstedt",
    named_by: null,
    color: "#ffff00",
    xpos: 10,
    ypos: 4
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Đồng",
    atomic_mass: "63.546",
    category: "kim loại chuyển tiếp",
    group: 11,
    period: 4,
    phase: "Rắn",
    summary: "Đồng dẫn điện tuyệt vời, dùng làm dây điện và ống nước. Là thành phần của đồng thau.",
    appearance: "đỏ cam",
    melt: 1357.77,
    boil: 2835,
    density: 8.96,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 11,
    ypos: 4
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Kẽm",
    atomic_mass: "65.38",
    category: "kim loại chuyển tiếp",
    group: 12,
    period: 4,
    phase: "Rắn",
    summary: "Kẽm dùng để mạ bảo vệ sắt thép. Hợp chất kẽm oxit dùng trong kem chống nắng.",
    appearance: "xám bạc",
    melt: 692.68,
    boil: 1180,
    density: 7.14,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 12,
    ypos: 4
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gali",
    atomic_mass: "69.723",
    category: "kim loại sau chuyển tiếp",
    group: 13,
    period: 4,
    phase: "Rắn",
    summary: "Gali tan chảy ở nhiệt độ gần thân người. Dùng trong đèn LED và chất bán dẫn.",
    appearance: "trắng bạc",
    melt: 302.91,
    boil: 2673,
    density: 5.91,
    discovered_by: "Lecoq de Boisbaudran",
    named_by: null,
    color: "#cccccc",
    xpos: 13,
    ypos: 4
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germani",
    atomic_mass: "72.630",
    category: "á kim",
    group: 14,
    period: 4,
    phase: "Rắn",
    summary: "Germani là chất bán dẫn quan trọng trong thời kỳ đầu của ngành điện tử.",
    appearance: "trắng bạc",
    melt: 1211.4,
    boil: 3106,
    density: 5.323,
    discovered_by: "Clemens Winkler",
    named_by: null,
    color: "#ff00ff",
    xpos: 14,
    ypos: 4
  },
  {
    number: 33,
    symbol: "As",
    name: "Asen",
    atomic_mass: "74.922",
    category: "á kim",
    group: 15,
    period: 4,
    phase: "Rắn",
    summary: "Asen nổi tiếng là chất độc, nhưng cũng dùng trong hợp kim và thuốc trừ sâu.",
    appearance: "xám kim loại",
    melt: 1090,
    boil: 887,
    density: 5.727,
    discovered_by: "Albertus Magnus",
    named_by: null,
    color: "#ff00ff",
    xpos: 15,
    ypos: 4
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selen",
    atomic_mass: "78.971",
    category: "phi kim đa nguyên tử",
    group: 16,
    period: 4,
    phase: "Rắn",
    summary: "Selen có tính quang điện, dùng trong máy photocopy và pin mặt trời.",
    appearance: "đen hoặc xám",
    melt: 494,
    boil: 958,
    density: 4.81,
    discovered_by: "Jöns Jacob Berzelius",
    named_by: null,
    color: "#3dff00",
    xpos: 16,
    ypos: 4
  },
  {
    number: 35,
    symbol: "Br",
    name: "Brom",
    atomic_mass: "79.904",
    category: "phi kim lưỡng nguyên tử",
    group: 17,
    period: 4,
    phase: "Lỏng",
    summary: "Brom là phi kim lỏng duy nhất, màu đỏ nâu, mùi hắc và rất độc.",
    appearance: "đỏ nâu",
    melt: 265.8,
    boil: 332,
    density: 3.1028,
    discovered_by: "Antoine Jérôme Balard",
    named_by: null,
    color: "#3dff00",
    xpos: 17,
    ypos: 4
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomic_mass: "83.798",
    category: "khí hiếm",
    group: 18,
    period: 4,
    phase: "Khí",
    summary: "Krypton dùng trong đèn flash chụp ảnh và laser công suất cao.",
    appearance: "khí không màu",
    melt: 115.78,
    boil: 119.93,
    density: 3.749,
    discovered_by: "William Ramsay",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 4
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidi",
    atomic_mass: "85.468",
    category: "kim loại kiềm",
    group: 1,
    period: 5,
    phase: "Rắn",
    summary: "Rubidi cực kỳ phản ứng, dùng trong đồng hồ nguyên tử độ chính xác cao.",
    appearance: "trắng bạc",
    melt: 312.46,
    boil: 961,
    density: 1.532,
    discovered_by: "Robert Bunsen",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 5
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Stronti",
    atomic_mass: "87.62",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 5,
    phase: "Rắn",
    summary: "Stronti tạo màu đỏ rực rỡ cho pháo hoa và pháo tín hiệu.",
    appearance: "vàng bạc",
    melt: 1050,
    boil: 1655,
    density: 2.64,
    discovered_by: "Adair Crawford",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 5
  },
  {
    number: 39,
    symbol: "Y",
    name: "Ytri",
    atomic_mass: "88.906",
    category: "kim loại chuyển tiếp",
    group: 3,
    period: 5,
    phase: "Rắn",
    summary: "Ytri dùng trong đèn LED, laser và làm chất siêu dẫn nhiệt độ cao.",
    appearance: "trắng bạc",
    melt: 1799,
    boil: 3609,
    density: 4.472,
    discovered_by: "Johan Gadolin",
    named_by: null,
    color: "#ffff00",
    xpos: 3,
    ypos: 5
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconi",
    atomic_mass: "91.224",
    category: "kim loại chuyển tiếp",
    group: 4,
    period: 5,
    phase: "Rắn",
    summary: "Zirconi chống ăn mòn tốt, dùng trong vỏ thanh nhiên liệu hạt nhân.",
    appearance: "trắng bạc",
    melt: 2128,
    boil: 4682,
    density: 6.52,
    discovered_by: "Martin Heinrich Klaproth",
    named_by: null,
    color: "#ffff00",
    xpos: 4,
    ypos: 5
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobi",
    atomic_mass: "92.906",
    category: "kim loại chuyển tiếp",
    group: 5,
    period: 5,
    phase: "Rắn",
    summary: "Niobi dùng trong thép hợp kim siêu bền và nam châm siêu dẫn.",
    appearance: "xám bạc",
    melt: 2750,
    boil: 5017,
    density: 8.57,
    discovered_by: "Charles Hatchett",
    named_by: null,
    color: "#ffff00",
    xpos: 5,
    ypos: 5
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molibden",
    atomic_mass: "95.95",
    category: "kim loại chuyển tiếp",
    group: 6,
    period: 5,
    phase: "Rắn",
    summary: "Molibden có điểm nóng chảy rất cao, dùng trong thép chịu nhiệt và chất bôi trơn.",
    appearance: "xám bạc",
    melt: 2896,
    boil: 4912,
    density: 10.28,
    discovered_by: "Carl Wilhelm Scheele",
    named_by: null,
    color: "#ffff00",
    xpos: 6,
    ypos: 5
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Tecneti",
    atomic_mass: "98",
    category: "kim loại chuyển tiếp",
    group: 7,
    period: 5,
    phase: "Rắn",
    summary: "Tecneti là nguyên tố nhân tạo đầu tiên, dùng rộng rãi trong y học hạt nhân.",
    appearance: "xám bạc",
    melt: 2430,
    boil: 4538,
    density: 11,
    discovered_by: "Emilio Segrè",
    named_by: null,
    color: "#ffff00",
    xpos: 7,
    ypos: 5
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Rutheni",
    atomic_mass: "101.07",
    category: "kim loại chuyển tiếp",
    group: 8,
    period: 5,
    phase: "Rắn",
    summary: "Rutheni là kim loại hiếm thuộc nhóm bạch kim, dùng làm chất xúc tác và trong điện tử.",
    appearance: "trắng bạc",
    melt: 2606,
    boil: 4423,
    density: 12.45,
    discovered_by: "Karl Ernst Claus",
    named_by: null,
    color: "#ffff00",
    xpos: 8,
    ypos: 5
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rodi",
    atomic_mass: "102.91",
    category: "kim loại chuyển tiếp",
    group: 9,
    period: 5,
    phase: "Rắn",
    summary: "Rodi là kim loại quý hiếm nhất, dùng trong bộ chuyển đổi xúc tác ô tô và trang sức.",
    appearance: "trắng bạc",
    melt: 2237,
    boil: 3968,
    density: 12.41,
    discovered_by: "William Hyde Wollaston",
    named_by: null,
    color: "#ffff00",
    xpos: 9,
    ypos: 5
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Paladi",
    atomic_mass: "106.42",
    category: "kim loại chuyển tiếp",
    group: 10,
    period: 5,
    phase: "Rắn",
    summary: "Paladi có khả năng hấp thụ hydro tuyệt vời, dùng trong lọc khí thải và nha khoa.",
    appearance: "trắng bạc",
    melt: 1828.05,
    boil: 3236,
    density: 12.023,
    discovered_by: "William Hyde Wollaston",
    named_by: null,
    color: "#ffff00",
    xpos: 10,
    ypos: 5
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Bạc",
    atomic_mass: "107.87",
    category: "kim loại chuyển tiếp",
    group: 11,
    period: 5,
    phase: "Rắn",
    summary: "Bạc dẫn điện và dẫn nhiệt tốt nhất. Dùng trong trang sức, tiền xu và nhiếp ảnh.",
    appearance: "trắng bóng",
    melt: 1234.93,
    boil: 2435,
    density: 10.49,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 11,
    ypos: 5
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadimi",
    atomic_mass: "112.41",
    category: "kim loại sau chuyển tiếp",
    group: 12,
    period: 5,
    phase: "Rắn",
    summary: "Cadimi dùng trong pin Ni-Cd và làm chất màu. Nó rất độc đối với môi trường.",
    appearance: "trắng bạc",
    melt: 594.22,
    boil: 1040,
    density: 8.65,
    discovered_by: "Karl Samuel Leberecht Hermann",
    named_by: null,
    color: "#cccccc",
    xpos: 12,
    ypos: 5
  },
  {
    number: 49,
    symbol: "In",
    name: "Indi",
    atomic_mass: "114.82",
    category: "kim loại sau chuyển tiếp",
    group: 13,
    period: 5,
    phase: "Rắn",
    summary: "Indi rất mềm, dùng làm màn hình cảm ứng LCD và gương soi chất lượng cao.",
    appearance: "trắng bạc",
    melt: 429.75,
    boil: 2345,
    density: 7.31,
    discovered_by: "Ferdinand Reich",
    named_by: null,
    color: "#cccccc",
    xpos: 13,
    ypos: 5
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Thiếc",
    atomic_mass: "118.71",
    category: "kim loại sau chuyển tiếp",
    group: 14,
    period: 5,
    phase: "Rắn",
    summary: "Thiếc dùng để mạ lon thực phẩm và làm hợp kim đồng thiếc (bronze).",
    appearance: "trắng bạc",
    melt: 505.08,
    boil: 2875,
    density: 7.287,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#cccccc",
    xpos: 14,
    ypos: 5
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimon",
    atomic_mass: "121.76",
    category: "á kim",
    group: 15,
    period: 5,
    phase: "Rắn",
    summary: "Antimon dùng trong chất chống cháy và làm cứng các hợp kim chì.",
    appearance: "xám bạc",
    melt: 903.78,
    boil: 1860,
    density: 6.697,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ff00ff",
    xpos: 15,
    ypos: 5
  },
  {
    number: 52,
    symbol: "Te",
    name: "Telu",
    atomic_mass: "127.60",
    category: "á kim",
    group: 16,
    period: 5,
    phase: "Rắn",
    summary: "Telu là á kim hiếm, dùng trong pin mặt trời và làm hợp kim với đồng, thép.",
    appearance: "trắng bạc",
    melt: 722.66,
    boil: 1261,
    density: 6.24,
    discovered_by: "Franz-Joseph Müller von Reichenstein",
    named_by: null,
    color: "#ff00ff",
    xpos: 16,
    ypos: 5
  },
  {
    number: 53,
    symbol: "I",
    name: "Iốt",
    atomic_mass: "126.90",
    category: "phi kim lưỡng nguyên tử",
    group: 17,
    period: 5,
    phase: "Rắn",
    summary: "Iốt cần thiết cho tuyến giáp. Ở dạng rắn nó có màu tím đen và thăng hoa thành hơi tím.",
    appearance: "tím đen",
    melt: 386.85,
    boil: 457.4,
    density: 4.933,
    discovered_by: "Bernard Courtois",
    named_by: null,
    color: "#3dff00",
    xpos: 17,
    ypos: 5
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomic_mass: "131.29",
    category: "khí hiếm",
    group: 18,
    period: 5,
    phase: "Khí",
    summary: "Xenon dùng trong đèn pha ô tô cường độ cao và làm thuốc gây mê.",
    appearance: "khí không màu",
    melt: 161.4,
    boil: 165.03,
    density: 5.894,
    discovered_by: "William Ramsay",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 5
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesi",
    atomic_mass: "132.91",
    category: "kim loại kiềm",
    group: 1,
    period: 6,
    phase: "Rắn",
    summary: "Cesi là kim loại kiềm phản ứng mạnh nhất, dùng định nghĩa giây trong đồng hồ nguyên tử.",
    appearance: "vàng bạc",
    melt: 301.59,
    boil: 944,
    density: 1.93,
    discovered_by: "Robert Bunsen",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 6
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Bari",
    atomic_mass: "137.33",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 6,
    phase: "Rắn",
    summary: "Bari dùng trong thăm dò dầu khí và làm chất cản quang trong chụp X-quang tiêu hóa.",
    appearance: "trắng bạc",
    melt: 1000,
    boil: 2170,
    density: 3.51,
    discovered_by: "Carl Wilhelm Scheele",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 6
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthan",
    atomic_mass: "138.91",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Lanthan là nguyên tố đầu tiên của nhóm Lanthan, dùng trong ống kính máy ảnh và pin xe lai.",
    appearance: "trắng bạc",
    melt: 1193,
    boil: 3737,
    density: 6.162,
    discovered_by: "Carl Gustaf Mosander",
    named_by: null,
    color: "#ffb6c1",
    xpos: 3,
    ypos: 9
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Ceri",
    atomic_mass: "140.12",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Ceri là nguyên tố lanthan phổ biến nhất, dùng trong đá lửa bật lửa và đánh bóng thủy tinh.",
    appearance: "trắng bạc",
    melt: 1068,
    boil: 3716,
    density: 6.77,
    discovered_by: "Martin Heinrich Klaproth",
    named_by: null,
    color: "#ffb6c1",
    xpos: 4,
    ypos: 9
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodym",
    atomic_mass: "140.91",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Praseodym dùng tạo màu vàng cho thủy tinh và trong nam châm cường độ cao.",
    appearance: "xám bạc",
    melt: 1208,
    boil: 3793,
    density: 6.77,
    discovered_by: "Carl Auer von Welsbach",
    named_by: null,
    color: "#ffb6c1",
    xpos: 5,
    ypos: 9
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodym",
    atomic_mass: "144.24",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Neodym dùng sản xuất nam châm vĩnh cửu mạnh nhất thế giới hiện nay.",
    appearance: "trắng bạc",
    melt: 1297,
    boil: 3347,
    density: 7.01,
    discovered_by: "Carl Auer von Welsbach",
    named_by: null,
    color: "#ffb6c1",
    xpos: 6,
    ypos: 9
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Prometi",
    atomic_mass: "145",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Prometi là nguyên tố phóng xạ nhân tạo, dùng trong pin hạt nhân siêu nhỏ.",
    appearance: "ánh kim",
    melt: 1315,
    boil: 3273,
    density: 7.26,
    discovered_by: "Chien Shiung Wu",
    named_by: null,
    color: "#ffb6c1",
    xpos: 7,
    ypos: 9
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samari",
    atomic_mass: "150.36",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Samari dùng trong nam châm chịu nhiệt độ cao và trong điều trị ung thư xương.",
    appearance: "trắng bạc",
    melt: 1345,
    boil: 2173,
    density: 7.52,
    discovered_by: "Lecoq de Boisbaudran",
    named_by: null,
    color: "#ffb6c1",
    xpos: 8,
    ypos: 9
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europi",
    atomic_mass: "151.96",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Europi là chất phát quang đỏ trong màn hình TV màu và đèn huỳnh quang.",
    appearance: "ánh kim",
    melt: 1099,
    boil: 1802,
    density: 5.244,
    discovered_by: "Eugène-Anatole Demarçay",
    named_by: null,
    color: "#ffb6c1",
    xpos: 9,
    ypos: 9
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolini",
    atomic_mass: "157.25",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Gadolini dùng làm chất tương phản trong chụp cộng hưởng từ MRI.",
    appearance: "trắng bạc",
    melt: 1585,
    boil: 3546,
    density: 7.9,
    discovered_by: "Jean Charles Galissard de Marignac",
    named_by: null,
    color: "#ffb6c1",
    xpos: 10,
    ypos: 9
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbi",
    atomic_mass: "158.93",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Terbi dùng trong đèn tiết kiệm năng lượng và các thiết bị sonar.",
    appearance: "trắng bạc",
    melt: 1629,
    boil: 3503,
    density: 8.23,
    discovered_by: "Carl Gustaf Mosander",
    named_by: null,
    color: "#ffb6c1",
    xpos: 11,
    ypos: 9
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosi",
    atomic_mass: "162.50",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Dysprosi dùng trong nam châm xe điện và thanh điều khiển lò phản ứng hạt nhân.",
    appearance: "trắng bạc",
    melt: 1680,
    boil: 2840,
    density: 8.54,
    discovered_by: "Lecoq de Boisbaudran",
    named_by: null,
    color: "#ffb6c1",
    xpos: 12,
    ypos: 9
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmi",
    atomic_mass: "164.93",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Holmi có từ tính mạnh nhất, dùng trong các cực nam châm và laser y tế.",
    appearance: "trắng bạc",
    melt: 1734,
    boil: 2993,
    density: 8.79,
    discovered_by: "Marc Delafontaine",
    named_by: null,
    color: "#ffb6c1",
    xpos: 13,
    ypos: 9
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbi",
    atomic_mass: "167.26",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Erbi dùng làm bộ khuếch đại tín hiệu trong cáp quang viễn thông.",
    appearance: "trắng bạc",
    melt: 1802,
    boil: 3141,
    density: 9.066,
    discovered_by: "Carl Gustaf Mosander",
    named_by: null,
    color: "#ffb6c1",
    xpos: 14,
    ypos: 9
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thuli",
    atomic_mass: "168.93",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Thuli là nguyên tố lanthan hiếm nhất, dùng trong máy X-quang cầm tay.",
    appearance: "xám bạc",
    melt: 1818,
    boil: 2223,
    density: 9.32,
    discovered_by: "Per Teodor Cleve",
    named_by: null,
    color: "#ffb6c1",
    xpos: 15,
    ypos: 9
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Yterbi",
    atomic_mass: "173.05",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Yterbi dùng trong đồng hồ nguyên tử và làm chất xúc tác hóa học.",
    appearance: "trắng bạc",
    melt: 1097,
    boil: 1469,
    density: 6.9,
    discovered_by: "Jean Charles Galissard de Marignac",
    named_by: null,
    color: "#ffb6c1",
    xpos: 16,
    ypos: 9
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Luteti",
    atomic_mass: "174.97",
    category: "lanthan",
    group: 3,
    period: 6,
    phase: "Rắn",
    summary: "Luteti là nguyên tố lanthan cuối cùng, dùng trong chụp PET y tế.",
    appearance: "trắng bạc",
    melt: 1925,
    boil: 3675,
    density: 9.84,
    discovered_by: "Georges Urbain",
    named_by: null,
    color: "#ffb6c1",
    xpos: 17,
    ypos: 9
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafni",
    atomic_mass: "178.49",
    category: "kim loại chuyển tiếp",
    group: 4,
    period: 6,
    phase: "Rắn",
    summary: "Hafni dùng trong thanh điều khiển hạt nhân và vi mạch điện tử cao cấp.",
    appearance: "xám bạc",
    melt: 2506,
    boil: 4876,
    density: 13.31,
    discovered_by: "Dirk Coster",
    named_by: null,
    color: "#ffff00",
    xpos: 4,
    ypos: 6
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantal",
    atomic_mass: "180.95",
    category: "kim loại chuyển tiếp",
    group: 5,
    period: 6,
    phase: "Rắn",
    summary: "Tantal cực kỳ chống ăn mòn, dùng làm tụ điện trong điện thoại di động.",
    appearance: "xám xanh",
    melt: 3290,
    boil: 5731,
    density: 16.69,
    discovered_by: "Anders Gustaf Ekeberg",
    named_by: null,
    color: "#ffff00",
    xpos: 5,
    ypos: 6
  },
  {
    number: 74,
    symbol: "W",
    name: "Vonfram",
    atomic_mass: "183.84",
    category: "kim loại chuyển tiếp",
    group: 6,
    period: 6,
    phase: "Rắn",
    summary: "Vonfram có điểm nóng chảy cao nhất trong các kim loại, dùng làm dây tóc bóng đèn.",
    appearance: "xám bạc",
    melt: 3695,
    boil: 6203,
    density: 19.25,
    discovered_by: "Carl Wilhelm Scheele",
    named_by: null,
    color: "#ffff00",
    xpos: 6,
    ypos: 6
  },
  {
    number: 75,
    symbol: "Re",
    name: "Reni",
    atomic_mass: "186.21",
    category: "kim loại chuyển tiếp",
    group: 7,
    period: 6,
    phase: "Rắn",
    summary: "Reni là kim loại cực hiếm, dùng trong động cơ phản lực chịu nhiệt độ cao.",
    appearance: "trắng bạc",
    melt: 3459,
    boil: 5869,
    density: 21.02,
    discovered_by: "Masataka Ogawa",
    named_by: null,
    color: "#ffff00",
    xpos: 7,
    ypos: 6
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmi",
    atomic_mass: "190.23",
    category: "kim loại chuyển tiếp",
    group: 8,
    period: 6,
    phase: "Rắn",
    summary: "Osmi là nguyên tố đặc nhất trong tự nhiên, dùng trong ngòi bút máy và tiếp điểm điện.",
    appearance: "xanh bạc",
    melt: 3306,
    boil: 5285,
    density: 22.59,
    discovered_by: "Smithson Tennant",
    named_by: null,
    color: "#ffff00",
    xpos: 8,
    ypos: 6
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridi",
    atomic_mass: "192.22",
    category: "kim loại chuyển tiếp",
    group: 9,
    period: 6,
    phase: "Rắn",
    summary: "Iridi cực kỳ chống ăn mòn, dùng trong bugi đánh lửa và các tiêu chuẩn đo lường.",
    appearance: "trắng bạc",
    melt: 2719,
    boil: 4403,
    density: 22.56,
    discovered_by: "Smithson Tennant",
    named_by: null,
    color: "#ffff00",
    xpos: 9,
    ypos: 6
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Bạch kim",
    atomic_mass: "195.08",
    category: "kim loại chuyển tiếp",
    group: 10,
    period: 6,
    phase: "Rắn",
    summary: "Bạch kim là kim loại quý, dùng làm trang sức cao cấp và chất xúc tác công nghiệp.",
    appearance: "trắng bạc",
    melt: 2041.4,
    boil: 4098,
    density: 21.45,
    discovered_by: "Antonio de Ulloa",
    named_by: null,
    color: "#ffff00",
    xpos: 10,
    ypos: 6
  },
  {
    number: 79,
    symbol: "Au",
    name: "Vàng",
    atomic_mass: "196.97",
    category: "kim loại chuyển tiếp",
    group: 11,
    period: 6,
    phase: "Rắn",
    summary: "Vàng là kim loại quý nhất, dẻo nhất, dùng làm tiền tệ, trang sức và trong điện tử.",
    appearance: "vàng kim loại",
    melt: 1337.33,
    boil: 3129,
    density: 19.3,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 11,
    ypos: 6
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Thủy ngân",
    atomic_mass: "200.59",
    category: "kim loại chuyển tiếp",
    group: 12,
    period: 6,
    phase: "Lỏng",
    summary: "Thủy ngân là kim loại lỏng duy nhất ở nhiệt độ thường, dùng trong nhiệt kế và đèn huỳnh quang.",
    appearance: "màu bạc",
    melt: 234.321,
    boil: 629.88,
    density: 13.534,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#ffff00",
    xpos: 12,
    ypos: 6
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thali",
    atomic_mass: "204.38",
    category: "kim loại sau chuyển tiếp",
    group: 13,
    period: 6,
    phase: "Rắn",
    summary: "Thali rất độc, từng được dùng làm thuốc diệt chuột. Nay dùng trong kính hồng ngoại.",
    appearance: "trắng bạc",
    melt: 577,
    boil: 1746,
    density: 11.85,
    discovered_by: "William Crookes",
    named_by: null,
    color: "#cccccc",
    xpos: 13,
    ypos: 6
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Chì",
    atomic_mass: "207.2",
    category: "kim loại sau chuyển tiếp",
    group: 14,
    period: 6,
    phase: "Rắn",
    summary: "Chì nặng, mềm, dùng trong ắc quy xe hơi và tấm chắn bảo vệ tia X.",
    appearance: "xám xanh",
    melt: 600.61,
    boil: 2022,
    density: 11.34,
    discovered_by: "Cổ đại",
    named_by: null,
    color: "#cccccc",
    xpos: 14,
    ypos: 6
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismut",
    atomic_mass: "208.98",
    category: "kim loại sau chuyển tiếp",
    group: 15,
    period: 6,
    phase: "Rắn",
    summary: "Bismut là kim loại nặng ít độc nhất, dùng trong dược phẩm và mỹ phẩm.",
    appearance: "trắng hồng ánh kim",
    melt: 544.7,
    boil: 1837,
    density: 9.78,
    discovered_by: "Claude François Geoffroy",
    named_by: null,
    color: "#cccccc",
    xpos: 15,
    ypos: 6
  },
  {
    number: 84,
    symbol: "Po",
    name: "Poloni",
    atomic_mass: "209",
    category: "kim loại sau chuyển tiếp",
    group: 16,
    period: 6,
    phase: "Rắn",
    summary: "Poloni là nguyên tố phóng xạ cực mạnh, được Marie Curie phát hiện và đặt tên theo Ba Lan.",
    appearance: "màu bạc",
    melt: 527,
    boil: 1235,
    density: 9.196,
    discovered_by: "Marie Curie",
    named_by: null,
    color: "#cccccc",
    xpos: 16,
    ypos: 6
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatin",
    atomic_mass: "210",
    category: "á kim",
    group: 17,
    period: 6,
    phase: "Rắn",
    summary: "Astatin là nguyên tố hiếm nhất trong tự nhiên, cực kỳ phóng xạ và có đời sống ngắn.",
    appearance: "đen",
    melt: 575,
    boil: 610,
    density: 7,
    discovered_by: "Dale R. Corson",
    named_by: null,
    color: "#ff00ff",
    xpos: 17,
    ypos: 6
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomic_mass: "222",
    category: "khí hiếm",
    group: 18,
    period: 6,
    phase: "Khí",
    summary: "Radon là khí hiếm phóng xạ, có thể tích tụ trong nhà và gây nguy cơ ung thư phổi.",
    appearance: "khí không màu",
    melt: 202,
    boil: 211.3,
    density: 9.73,
    discovered_by: "Friedrich Ernst Dorn",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 6
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Fransi",
    atomic_mass: "223",
    category: "kim loại kiềm",
    group: 1,
    period: 7,
    phase: "Rắn",
    summary: "Fransi là kim loại kiềm cực hiếm và phóng xạ mạnh, chỉ tồn tại trong thời gian ngắn.",
    appearance: "ánh kim",
    melt: 300,
    boil: 950,
    density: 1.87,
    discovered_by: "Marguerite Perey",
    named_by: null,
    color: "#ff00ff",
    xpos: 1,
    ypos: 7
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radi",
    atomic_mass: "226",
    category: "kim loại kiềm thổ",
    group: 2,
    period: 7,
    phase: "Rắn",
    summary: "Radi là nguyên tố phóng xạ nổi tiếng dùng trong điều trị ung thư thời kỳ đầu.",
    appearance: "trắng bạc",
    melt: 973,
    boil: 2010,
    density: 5.5,
    discovered_by: "Marie Curie",
    named_by: null,
    color: "#ff7f00",
    xpos: 2,
    ypos: 7
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actini",
    atomic_mass: "227",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Actini là nguyên tố đầu tiên của nhóm Actini, phát ra ánh sáng xanh lam mờ trong bóng tối.",
    appearance: "trắng bạc",
    melt: 1323,
    boil: 3471,
    density: 10,
    discovered_by: "André-Louis Debierne",
    named_by: null,
    color: "#10b981",
    xpos: 3,
    ypos: 10
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thori",
    atomic_mass: "232.04",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Thori là nhiên liệu hạt nhân tiềm năng thay thế urani vì an toàn và dồi dào hơn.",
    appearance: "trắng bạc",
    melt: 2023,
    boil: 5061,
    density: 11.7,
    discovered_by: "Jöns Jacob Berzelius",
    named_by: null,
    color: "#10b981",
    xpos: 4,
    ypos: 10
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactini",
    atomic_mass: "231.04",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Protactini là nguyên tố phóng xạ hiếm, cực kỳ độc và có tính phóng xạ cao.",
    appearance: "trắng bạc",
    melt: 1841,
    boil: 4300,
    density: 15.37,
    discovered_by: "William Crookes",
    named_by: null,
    color: "#10b981",
    xpos: 5,
    ypos: 10
  },
  {
    number: 92,
    symbol: "U",
    name: "Urani",
    atomic_mass: "238.03",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Urani là nhiên liệu chính cho các lò phản ứng hạt nhân và vũ khí nguyên tử.",
    appearance: "trắng bạc",
    melt: 1405.3,
    boil: 4404,
    density: 18.95,
    discovered_by: "Martin Heinrich Klaproth",
    named_by: null,
    color: "#10b981",
    xpos: 6,
    ypos: 10
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptuni",
    atomic_mass: "237",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Neptuni là nguyên tố siêu urani đầu tiên được tổng hợp nhân tạo.",
    appearance: "trắng bạc",
    melt: 917,
    boil: 4273,
    density: 20.45,
    discovered_by: "Edwin McMillan",
    named_by: null,
    color: "#10b981",
    xpos: 7,
    ypos: 10
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutoni",
    atomic_mass: "244",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Plutoni là nguyên tố phóng xạ quan trọng trong năng lượng và vũ khí hạt nhân.",
    appearance: "trắng bạc",
    melt: 912.5,
    boil: 3501,
    density: 19.84,
    discovered_by: "Glenn T. Seaborg",
    named_by: null,
    color: "#10b981",
    xpos: 8,
    ypos: 10
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americi",
    atomic_mass: "243",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Americi dùng trong các thiết bị báo cháy ion hóa phổ biến trong gia đình.",
    appearance: "trắng bạc",
    melt: 1449,
    boil: 2880,
    density: 12,
    discovered_by: "Glenn T. Seaborg",
    named_by: null,
    color: "#10b981",
    xpos: 9,
    ypos: 10
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curi",
    atomic_mass: "247",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Curi dùng làm nguồn năng lượng cho các thiết bị thăm dò vũ trụ xa xôi.",
    appearance: "trắng bạc",
    melt: 1613,
    boil: 3383,
    density: 13.51,
    discovered_by: "Glenn T. Seaborg",
    named_by: null,
    color: "#10b981",
    xpos: 10,
    ypos: 10
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkeli",
    atomic_mass: "247",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Berkeli là nguyên tố nhân tạo, dùng chủ yếu trong nghiên cứu khoa học cơ bản.",
    appearance: "trắng bạc",
    melt: 1259,
    boil: 2900,
    density: 14.78,
    discovered_by: "Glenn T. Seaborg",
    named_by: null,
    color: "#10b981",
    xpos: 11,
    ypos: 10
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californi",
    atomic_mass: "251",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Californi là nguồn phát neutron mạnh, dùng trong khởi động lò phản ứng hạt nhân.",
    appearance: "ánh kim",
    melt: 1173,
    boil: 1743,
    density: 15.1,
    discovered_by: "Glenn T. Seaborg",
    named_by: null,
    color: "#10b981",
    xpos: 12,
    ypos: 10
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteini",
    atomic_mass: "252",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Einsteini được phát hiện trong tàn dư của vụ thử bom hydro đầu tiên.",
    appearance: "trắng bạc",
    melt: 1133,
    boil: 1269,
    density: 8.84,
    discovered_by: "Lawrence Berkeley National Laboratory",
    named_by: null,
    color: "#10b981",
    xpos: 13,
    ypos: 10
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermi",
    atomic_mass: "257",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Fermi là nguyên tố nặng nhất có thể tạo ra bằng cách bắn phá neutron.",
    appearance: "chưa rõ",
    melt: 1800,
    boil: null,
    density: null,
    discovered_by: "Lawrence Berkeley National Laboratory",
    named_by: null,
    color: "#10b981",
    xpos: 14,
    ypos: 10
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevi",
    atomic_mass: "258",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Mendelevi được đặt tên theo Dmitri Mendeleev, người tạo ra bảng tuần hoàn.",
    appearance: "chưa rõ",
    melt: 1100,
    boil: null,
    density: null,
    discovered_by: "Lawrence Berkeley National Laboratory",
    named_by: null,
    color: "#10b981",
    xpos: 15,
    ypos: 10
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobeli",
    atomic_mass: "259",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Nobeli được đặt tên theo Alfred Nobel, người sáng lập giải thưởng Nobel.",
    appearance: "chưa rõ",
    melt: 1100,
    boil: null,
    density: null,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#10b981",
    xpos: 16,
    ypos: 10
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrenci",
    atomic_mass: "266",
    category: "actini",
    group: 3,
    period: 7,
    phase: "Rắn",
    summary: "Lawrenci là nguyên tố cuối cùng của nhóm Actini, cực kỳ phóng xạ.",
    appearance: "chưa rõ",
    melt: 1900,
    boil: null,
    density: null,
    discovered_by: "Lawrence Berkeley National Laboratory",
    named_by: null,
    color: "#10b981",
    xpos: 17,
    ypos: 10
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordi",
    atomic_mass: "267",
    category: "kim loại chuyển tiếp",
    group: 4,
    period: 7,
    phase: "Rắn",
    summary: "Rutherfordi là nguyên tố siêu nặng nhân tạo, có đời sống cực ngắn.",
    appearance: "chưa rõ",
    melt: 2400,
    boil: 5800,
    density: 23.2,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#ffff00",
    xpos: 4,
    ypos: 7
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubni",
    atomic_mass: "268",
    category: "kim loại chuyển tiếp",
    group: 5,
    period: 7,
    phase: "Rắn",
    summary: "Dubni là nguyên tố tổng hợp nhân tạo, đặt tên theo thành phố Dubna của Nga.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 29.3,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#ffff00",
    xpos: 5,
    ypos: 7
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgi",
    atomic_mass: "269",
    category: "kim loại chuyển tiếp",
    group: 6,
    period: 7,
    phase: "Rắn",
    summary: "Seaborgi đặt tên theo Glenn Seaborg, người phát hiện nhiều nguyên tố siêu urani.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 35,
    discovered_by: "Lawrence Berkeley National Laboratory",
    named_by: null,
    color: "#ffff00",
    xpos: 6,
    ypos: 7
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohri",
    atomic_mass: "270",
    category: "kim loại chuyển tiếp",
    group: 7,
    period: 7,
    phase: "Rắn",
    summary: "Bohri đặt tên theo nhà vật lý Niels Bohr, người có công lớn trong cấu tạo nguyên tử.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 37,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 7,
    ypos: 7
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassi",
    atomic_mass: "269",
    category: "kim loại chuyển tiếp",
    group: 8,
    period: 7,
    phase: "Rắn",
    summary: "Hassi là nguyên tố siêu nặng, đặt tên theo bang Hesse của Đức.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 41,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 8,
    ypos: 7
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitneri",
    atomic_mass: "278",
    category: "kim loại chuyển tiếp",
    group: 9,
    period: 7,
    phase: "Rắn",
    summary: "Meitneri đặt tên theo Lise Meitner, người đồng phát hiện ra sự phân hạch hạt nhân.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 37.4,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 9,
    ypos: 7
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadti",
    atomic_mass: "281",
    category: "kim loại chuyển tiếp",
    group: 10,
    period: 7,
    phase: "Rắn",
    summary: "Darmstadti đặt tên theo thành phố Darmstadt của Đức, nơi nó được phát hiện.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 34.8,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 10,
    ypos: 7
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgeni",
    atomic_mass: "282",
    category: "kim loại chuyển tiếp",
    group: 11,
    period: 7,
    phase: "Rắn",
    summary: "Roentgeni đặt tên theo Wilhelm Röntgen, người phát hiện ra tia X.",
    appearance: "chưa rõ",
    melt: null,
    boil: null,
    density: 28.7,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 11,
    ypos: 7
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernici",
    atomic_mass: "285",
    category: "kim loại chuyển tiếp",
    group: 12,
    period: 7,
    phase: "Rắn",
    summary: "Copernici đặt tên theo nhà thiên văn học Nicolaus Copernicus.",
    appearance: "chưa rõ",
    melt: null,
    boil: 357,
    density: 23.7,
    discovered_by: "Gesellschaft für Schwerionenforschung",
    named_by: null,
    color: "#ffff00",
    xpos: 12,
    ypos: 7
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihoni",
    atomic_mass: "286",
    category: "kim loại sau chuyển tiếp",
    group: 13,
    period: 7,
    phase: "Rắn",
    summary: "Nihoni là nguyên tố đầu tiên được phát hiện tại một quốc gia châu Á (Nhật Bản).",
    appearance: "chưa rõ",
    melt: 700,
    boil: 1400,
    density: 16,
    discovered_by: "RIKEN",
    named_by: null,
    color: "#cccccc",
    xpos: 13,
    ypos: 7
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovi",
    atomic_mass: "289",
    category: "kim loại sau chuyển tiếp",
    group: 14,
    period: 7,
    phase: "Rắn",
    summary: "Flerovi là nguyên tố siêu nặng, đặt tên theo phòng thí nghiệm Flerov của Nga.",
    appearance: "chưa rõ",
    melt: 340,
    boil: 420,
    density: 14,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#cccccc",
    xpos: 14,
    ypos: 7
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovi",
    atomic_mass: "290",
    category: "kim loại sau chuyển tiếp",
    group: 15,
    period: 7,
    phase: "Rắn",
    summary: "Moscovi đặt tên theo vùng Moscow của Nga, nơi nó được tổng hợp.",
    appearance: "chưa rõ",
    melt: 670,
    boil: 1400,
    density: 13.5,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#cccccc",
    xpos: 15,
    ypos: 7
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermori",
    atomic_mass: "293",
    category: "kim loại sau chuyển tiếp",
    group: 16,
    period: 7,
    phase: "Rắn",
    summary: "Livermori đặt tên theo Phòng thí nghiệm Quốc gia Lawrence Livermore của Mỹ.",
    appearance: "chưa rõ",
    melt: 709,
    boil: 1085,
    density: 12.9,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#cccccc",
    xpos: 16,
    ypos: 7
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomic_mass: "294",
    category: "phi kim lưỡng nguyên tử",
    group: 17,
    period: 7,
    phase: "Rắn",
    summary: "Tennessine đặt tên theo bang Tennessee của Mỹ, trung tâm nghiên cứu hạt nhân.",
    appearance: "chưa rõ",
    melt: 723,
    boil: 883,
    density: 7.2,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#3dff00",
    xpos: 17,
    ypos: 7
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomic_mass: "294",
    category: "khí hiếm",
    group: 18,
    period: 7,
    phase: "Rắn",
    summary: "Oganesson là nguyên tố cuối cùng của bảng tuần hoàn hiện nay, đặt tên theo Yuri Oganessian.",
    appearance: "chưa rõ",
    melt: 323,
    boil: 353,
    density: 5,
    discovered_by: "Joint Institute for Nuclear Research",
    named_by: null,
    color: "#ff0000",
    xpos: 18,
    ypos: 7
  },
];
